version: "3"

dotenv: [".env"]

tasks:
  install:
    cmds:
      - uv sync --dev
      - uv run pre-commit install

  run:
    dir: clerk_api_demo
    cmds:
      - uv run reflex run

  test:
    cmds:
      - uv run pytest

  lint:
    cmds:
      - uv run ruff check .

  typecheck:
    cmds:
      - uv run pyright

  bump-patch:
    cmds:
      - uv run scripts/bump-version.py patch pyproject.toml

  bump-minor:
    cmds:
      - uv run scripts/bump-version.py patch pyproject.toml

  bump-major:
    cmds:
      - uv run scripts/bump-version.py patch pyproject.toml

  push-tag:
    cmds:
      - uv run scripts/get-version.py pyproject.toml | xargs -I {} git tag -s v{} -m "Release v{}"

  pre-commit-all:
    cmds:
      - uv run pre-commit run --all-files

  pre-commit-update:
    cmds:
      - uv run pre-commit autoupdate

  publish:
    preconditions:
      # Check environment variable
      - sh: test -n "$PYPI_TOKEN"
        msg: "PYPI_TOKEN is not set -- Add PYPI_TOKEN=... to .env file"
    cmds:
      - echo "Publishing to PyPI"
      - uv run reflex component publish --no-validate-project-info --no-share --token $PYPI_TOKEN

  share:
    desc: Share the component via the reflex library
    cmds:
      - uv run reflex component share
