version: "3"

dotenv: [".env"]

tasks:
  install:
    cmds:
      - uv sync --dev
      - uv run pre-commit install

  run:
    dir: clerk_api_demo
    cmds:
      - uv run reflex run

  run-docs:
    cmds:
      # Use non-default port to not clash with reflex backend
      - uv run mkdocs serve -a localhost:9000

  publish-docs:
    cmds:
      - uv run mkdocs gh-deploy --force

  test:
    deps:
      - task: lint
      - task: typecheck
    cmds:
      - uv run playwright install chromium
      - uv run pytest

  lint:
    cmds:
      - uv run ruff check .

  typecheck:
    cmds:
      - uv run pyright

  bump-patch:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - uv run scripts/bump-version.py patch pyproject.toml README.md
      - uv lock

  bump-minor:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - uv run scripts/bump-version.py minor pyproject.toml README.md
      - uv lock

  bump-major:
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - uv run scripts/bump-version.py major pyproject.toml README.md
      - uv lock

  push-tag:
    preconditions:
      - sh: git status
    cmds:
      - git diff --quiet --staged || (echo "There are staged changes. They must be committed first" && exit 1)
      - git diff --quiet || (echo "There are unstaged changes. They must be committed first." && exit 1)

      - uv run scripts/get-version.py pyproject.toml | xargs -I {} git tag -a v{} -m "Release v{}"
      - git push --follow-tags

  pre-commit-all:
    cmds:
      - uv run pre-commit run --all-files

  pre-commit-update:
    cmds:
      - uv run pre-commit autoupdate

  publish:
    preconditions:
      # Check environment variable
      - sh: test -n "$PYPI_TOKEN"
        msg: "PYPI_TOKEN is not set -- Add PYPI_TOKEN=... to .env file"
    cmds:
      - echo "Publishing to PyPI"
      - uv run reflex component publish --no-validate-project-info --no-share --token $PYPI_TOKEN

  share:
    desc: Share the component via the reflex library
    cmds:
      - uv run reflex component share
