name: 'Setup Python Environment'
description: 'Sets up Python, uv, and Task for CI'
inputs:
  python-version:
    description: 'Python version to setup'
    required: true
  github-token:
    description: 'GitHub token for Task installation'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.5"

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ inputs.github-token }}
